### ISSUE TITLE
Bug In Strength Calculation

### ISSUE THREAD

**Issue by kyrashelwo** [Sesu8642/FeudalTactics#11]
Hi! First of all thanks for the awesome game and the readable code!

I noticed that sometimes it seems I have all my fields covered but then they get conquered by peasants anyways. First I thought it was just that I missed that gap in my defenses but now I caught the bug red-handed:

![strengthErrorMarked](https://user-images.githubusercontent.com/6185722/187172792-44c9338c-34e6-49e0-a10f-e65c20975579.png)

The blue dots indicate where my kingdom was connected. The dark blue dot was my capital (If I remember correctly). One of the light blue dots was part of the connection as well (don't remember which one).

The screenshot shows the state immediately when I got control for my turn again after the kingdom being separated.

Money of the lower part of the kingdom is 5, which is consistent with it's capital being destroyed after being separated from the upper kingdom by cutting the light blue dots. Money of the upper kingdom is 14, so it looks like the process was:  1. separation by conquering light blue, 2. destruction of lower kingdoms capital.

I think both tiles were covered by the (former) capital but even if I misremember from the Image it is clear that brown shouldn't have been able to conquer the dark blue tile, because either it was the capital or the capital was already where it is right now. In both cases it can't be conquered. I am 100% sure that the "new" capital is the one in the top kingdom next to the tree.

I had a look at the code already, but so far I couldn't find out whats wrong. Maybe something with getStrength() or getOffenseTileScoreInfo()?

I am running with ./gradlew desktop:run on commit 31f8dee3c1b02413f3634ad576d0de7ffe4441a4 in linux.

**Comment by Sesu8642** [comment]
Thanks for reporting! I will try to write a unit test that plays a couple of games and checks if something like this happens.
