### ISSUE TITLE
Being able to place stronger units immediately

### ISSUE THREAD

**Issue by d-albrecht** [Sesu8642/FeudalTactics#23]
In the current version of this game the only option to place newly bought units is to place a peasant onto an own kingdom tile. But there are cases in which I have 20 or more money but no free kingdom tiles to combine the unit to a spearman (imagine a two-tile kingdom with a capital and a castle). Or the only tile to combine them would be any that ended this unit's turn (a tree for example). But if I were able to create spearmen, I would be able to conquer something. Based on what I have read of the AI code, I'm pretty sure that the bots could do that. So, human players are in a bit of a disadvantage here. Based on videos of Slay I watched so far, this game offered this option as well.

**Comment by Sesu8642** [comment]
Right. The bots can do that so the player should be able to as well. If you have a unit "in your hand" and buy another one, they could be combined.

**Comment by d-albrecht** [comment]
That would be one way. This would also mean that I could pick up an already placed peasant, realize that I can't place him where I wanted him, while he was still picked up upgrade him, and place the combined spearman. I guess that could be the most straight forward way without messing too much with the game UI.
