### ISSUE TITLE
Do not force screen rotation

### ISSUE THREAD

**Issue by supermamie** [Sesu8642/FeudalTactics#27]
Most of the time, screen rotation is disabled on my phone.
But this game still rotate.
Is it possible to stay in portrait mode if the phone is conhigured not to rotate ?

**Comment by Sesu8642** [comment]
Interesting observation. I did not configure this explicitly. It seems to be some (default?) behavior from LibGDX. Need to investigate.

**Comment by Sesu8642** [comment]
I recently noticed the following in the AndroidManifest.xml:
`android:screenOrientation="sensor"`

By using unspecified instead, the system setting should be used. See also: https://www.javatpoint.com/android-screen-orientation-example
