### ISSUE TITLE
Compatibility with newer Java versions?

### ISSUE THREAD

**Issue by d-albrecht** [Sesu8642/FeudalTactics#30]
I'm definitely not new to the JVM but gradle poses some problems to me from time to time. So, I hope I'm not totally wrong with asking this question here.

When I was installing java (independent of this game), I was going for the most compatible JVM version and I decided to install version 17 (specifically openjdk version "17.0.4.1" at this point). But I ran into problems launching this game using the wiki guide. Because when I attempt to run the desktop:run command (or even launch gradle without any actions) I get the following error message:
````
Could not compile settings file '/home/alex/Documents/projects/FeudalTactics/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
````
As I said, each time I'm confronted with gradle, I still have to get familiar with it again, so I did a bit of research and tried a few things to make it compile/run. But all failed:
- Specifying JDK 17 in several ways I found online resulted in the same message.
- Running the project with a newer installed gradle version caused incompatibilities (see next point, essentially the exact same message)
- Upgrading the wrapper with the installed version caused a "build.gradle not compatible with newer gradle versions" message
- Upgrading the wrapper using the wrapper action cause the "unsupported class file version" error again

I used a newer gradle version explicitly because the "unsupported class file version" message suggests that running older gradle projects with newer JVM versions will not work at all for some reason and the gradle docs (at least if interpreted in some way) seem to support that idea. Which to me seems odd, though: A more recent compiler/JVM should always be able to handle older class files / gradle configs, so I'm a bit lost here.

A few questions at this point because I don't want to mess around with my system too much in case you can already tell me this:
- Is there a reason for using an older (already deprecated) gradle version? This seems to be the main problem for me.
- Do you know what the gradle-JVM-compatibility is supposed to indicate? Because to me this should only mean that with gradle version xx you can't compile source files newer then java version yy, but (somewhat) independent from the compiler version used (usually this shouldn't mean that the compiler **can't be more recent** then version yy).
- Is it possible that java 8 is more or less the only exact version that can compile/run this project? If this is the case, you should make this explicit in the wiki. Because both version 8 and version 17 are LTS versions and the JVM is usually perfectly compatible with older sources.

**Comment by Sesu8642** [comment]
Indeed the used Gradle version is probably not compatible with Java 17. I am not a Gradle expert either, that's why I try not to diverge from the default libGDX project setup too much. It's also the reason why I use this exact Gradle version. However, I think I might have messed something up when updating Gradle the last time. The F-Droid build showed some warning about the wrapper not being the same version that's specified somewhere else. That's still on my TODO list.

The newest Java version that is compatible with libGDX's Android support is 8. I am not sure if you can build the desktop version with a newer Java, I never tried. But I know that the desktop releases run fine with Java 11.

The easiest way to get the build running is probably to install Java 8 alongside your existing Java 17. You then need to point Gradle to Java 8. You could also try Java 11. If you do, please report back. I will adjust the wiki accordingly.

**Comment by Sesu8642** [comment]
I upgraded the wrapper to version 7.3.3 which is the one used by the setup tool of libGDX 1.11.0.

**Comment by d-albrecht** [comment]
So, I ended up installing Java8 and all works well. But with the update to grade 7.3.3 this perhaps wasn't even necessary. But I installed Java8 before I realized that this gradle version could be high enough for Java17.

The only thing is, isn't it a configuration error that launching the desktop app can fail when no android environment is present? Why should gradle attempt to compile against android anyway if I specify another target platform entirely? But again, I'm no gradle expert.

**Comment by d-albrecht** [comment]
Because I was lazy and didn't check the used java version today and actually used the newer one, I can say for a fact now that the new wrapper seems fully compatible with Java 17. Hence, you could edit the wiki to reflect this. Ideally you should point out somewhere that Java 17 isn't necessary, though, some might still use Java 8 and don't have to upgrade because of this project.
