### ISSUE TITLE
When do gravestone turn into trees?

### ISSUE THREAD

**Issue by d-albrecht** [Sesu8642/FeudalTactics#31]
I just played the current development version (by the way, it would probably be best if you changed to version number to something other than a stable version, for example v1.0.1-dev, or v 1.0.1-alpha, etc). In this match brown lost all its units and they turned into gravestones. But before it was brown's turn again, the gravestones turned into trees. Don't recall the order of players exactly, I can post parts of the log tomorrow, but let's just say, after brown was my turn, then came pink, then white, then the gravestones transformed, then came green and yellow and then was brown again. Shouldn't that process wait until it's brown's turn again?

**Comment by d-albrecht** [comment]
Okay, I apparently lost the interesting part of the log because there just were too many lines of log and the interesting messages got washed away by all the newer messages. ;)

But I have some other observation with trees that ties into this, I think. I surrounded a single-tile-territory with a (normal) tree on it, and it never spread to my tiles. Palm trees spread even if they are on single-tile-territories. And I think no trees can appear based on pure RNG anymore, so you should update the tutorial at some point.

That said, I feel like the spreading of trees in general behaves unnatural. They only spread when it's the color's turn of the tile they are on, right? I would instead suggest to let trees spread after every player acted, but with a lower percentage and with some cool-down. So, after a tree has spread, the spreading tree as well as the new tree can't spread again until x players have acted again. And after the cool-down has run out, they won't spread with their full y% but with a lower percentage, but will check for spreading not only after one of six players has played, but after every one.

**Comment by Sesu8642** [comment]
I have seen the gravestone thing before. Indeed the player should have one turn to remove them before they become trees. No need to post the logs for that but thanks!

I have changed the tree behaviour. Updating the tutorial is still a TODO for me. The rules are the following:

Trees no longer spawn randomly. Instead, they grow from gravestones or spawn if a capital is cut off from the rest of the kingdom. The tree type depends on the location of the tile. Coast tiles get palm trees and non-coast tiles get regular trees.

Regular trees only spread when there are at least two of them next to each other. This I think is true to the original.
Each pair of regular trees produces one new tree per turn and none of these can take part in spreading for the rest of the turn. This means that when there is a group of three, only a single new tree will spawn. I am not certain that this is exactly like in Slay but it seemed balanced. Regular trees cannot spread to coast tiles.

Palm trees always spread when they have an empty coast tile next to them. Each one spawn one new palm tree per turn.

I think that the trigger for spreading is already the way you describe - after every "round". I actually like that the new rules are very predictable and there is not a lot of chance involved. Do you think that they spread too fast now?

**Comment by d-albrecht** [comment]
I think what I get from that seems reasonable, but just to rephrase a bit (there isn't always a clear yes/no preference, the idea is to start a discussion in case you are unclear which approach you prefer):

There are only two sources of trees left, right? Those that are there at the beginning of the match and those that appear because of dead units and closed off capitals/units. That definitely is more predictable. Can trees spread before every player has acted once? If so, this might further put players into a disadvantage who are last in order.

Gravestones on (for example) **my** tiles appear when it's my turn and I can't pay all units and they turn into trees exactly before it's my turn again. And won't spread until it's my turn once again. What if I'm defeated before they can transform or spread?

Palm trees spread no matter the color of the neighboring tile? When will they spread? Only if it's the turn of the color the palm tree is on? What if this player is already defeated? When a palm tree spreads onto a tile with a different color, when will this new palm tree attempt to spread? Can these new palm trees immediately spread again if the color they land on is the exact next player? If so, should there be a delay instead?

Normal trees only spread when there are at least two next to each other, so my observation was totally in line. If there is a cluster of four trees (not placed in a "star" pattern) will the game always produce two new trees or is it possible that only one new tree appears? When will they spread? Especially if they are on different colors? Is it necessary and is it also faithful to the original game to prevent normal trees from spreading onto coast tiles?

In general, if the spreading depends on the color they are on, do they spread before it's this color's turn or after? If they spread before, this can be problematic in the first round because larger parts of my kingdoms can be covered before I even had a chance to counteract them and I will earn less. Is it reasonable to consider rounds when it comes to tree spreading in general? Or should any logic be independent of whether it's a tree on the first player's tile or the last player's?

If spreading doesn't depend on tile colors: how natural is it that they only spread after all six players have acted? Wouldn't a more organic approach be if they potentially could spread after/before any player? But then you would run into many of the other questions I asked before. But that was what I was suggesting before.

I think that are all the questions that came to my mind. You don't have to answer EVERYONE of them in the tutorial obviously, I just want to know those details and the questions can help you to check whether your concept and implementation are sound.

**Comment by Sesu8642** [comment]
I changed the behaviour. It is indeed more intuitive for gravestones to turn into trees when the player's turn starts.
You gave me the solution for cut off units in the other issue ;D They will now survive until the next turn of the owning player as well and then turn into gravestones. This way, it is guaranteed that the player has a chance to remove the gravestone before it turns into a tree. Let's hope I didn't break too many things in the process x)
