### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Sesu8642/FeudalTactics#36]
https://monitor.f-droid.org/builds/log/de.sesu8642.feudaltactics/2#site-footer

This is a known issue of AGP 4.1, could you please upgrade it to 4.2 or above? Thanks!

**Comment by Sesu8642** [comment]
Thanks for letting me know! I will try to fix it soon.

**Comment by Sesu8642** [comment]
I did a test build and it seems to work now:
https://gitlab.com/Sesu8642/fdroiddata/-/pipelines/760565556

**Comment by linsui** [comment]
Thanks!
