### ISSUE TITLE
Hard Game crash

### ISSUE THREAD

**Issue by d-albrecht** [Sesu8642/FeudalTactics#39]
I played a match today and at some point, the game hard crashed. Reopening the game put me in the situation I was in before and could finish the (almost won) game.

This crash apparently was at the exact time where the "you have almost captured the world, want to end here?" message box would normally appear. Because I never got the message in this match before or after the crash.

The seed was: 1675510407298 (medium size and density) with AI level hard

And here's the screenshot of the point in time it crashed / how it looked after reopening:
![ft_crash](https://user-images.githubusercontent.com/5196458/216766117-99126dc3-c07c-491c-9889-a947c8ca3bb6.png)

**Comment by Sesu8642** [comment]
Thanks for reporting! I'm pretty sure that I got it but please re-open if it happens again.
