### ISSUE TITLE
Questions about new initial game state

### ISSUE THREAD

**Issue by d-albrecht** [Sesu8642/FeudalTactics#41]
I saw/experienced that you changed/capped the initial amount of money of the kingdoms. I have a few questions about and problems with the new state.

1. Question: Does the reduced amount of money play a role in the player order? Because while larger kingdoms still mean higher income overall, the new capped amount can mean that a player with a single very large kingdom can come last, but several other players might have more money (summed over all kingdoms) and can quickly/easily sabotage the large-kingdom-player. So, either the ordering is according to kingdom size or money. Both wouldn't be ideal. But as - after the first round - player ordering doesn't make much of a difference, I think that the initial money should primarily be responsible for the first round (and therefore overall) player ordering.
2. Problem: When some other player moves first and can take some tiles from you, this reduces the initial amount of money. The problem I have with this situation is that if some other player cuts off some tiles and you still have at least four tiles, then you start off with less then 20 money. I feel like the "capping to 20" and the "reduced money at the start" negatively synergize to further penalize the players that move last.
3. Question: What made you choose 20 in particular? The capping was done to stop some players taking over too many already owned tiles, right? Then why exactly 20? That still means that the early players can capture owned tiles. To make players act more defensively, I probably would have chosen 15 (assuming some absolute cap). That means all players with at least three tiles can still buy a castle, but can't capture foreign territory.
4. Problem (sort of): I feel like the capping to 20 is rather arbitrary. And I'm not sure if this is the right way. I think it could be more appropriate to apply some function to the number of tiles, that still give you more money for more tiles, but the additional money decreased with more tiles. 2 => 10, 3 => 15 (so that you are still able to buy a castle first turn), 4 => 19 (only +4), 5 => 22 (+3), ..., to the point that starting from some tile-amount you only get 1 money more per additional tile. Or something similar. As +5, +4, +3, +2, +1, +1 would get really small very quick, you could also use +5, +4, +4, +3, +3, +3, +2, +2, +2, +2, +1, ... Or something in between.

**Comment by Sesu8642** [comment]
1. no
3. 20 allows the owner of a large kingdom to buy 2 units which can be used to protect the kingdom. Of course, they can only protect what is left when their first turn starts.

The problems you point out are very valid. The cap I implemented is not meant to be final. It was a quick solution for the large, overpowered kingdoms. I kept #35 open for further improvements. Let's continue the discussion there.
