### ISSUE TITLE
Ability to abandon units

### ISSUE THREAD

**Issue by YurishoSan** [Sesu8642/FeudalTactics#46]
In cases where i can see I wont be able to sustain the whole army tbe next turn, it should be a valid tactic to decrese army size in advance as to not forfiet the entire army.

This will allow "rush" tactics that eat the money reserves for a direct attack, for example to target an enemy castle, and then cut down the army size before it implodes.

Another use for this mechanic is to decrese army size in order to facilitate a baron. When I know I need a baron i currently need to avoid making speerman, as they block me financialy from making the baron. killing the speerman when the time comes will allow me to make the baron when needed without secrificing my military power before hand. This at the cost of killing the spearman.

This last mechanic should be considered in opossition to the possibility of combining spearman to create a baron, in which case the cost of the spearmen will not be waisted.

**Comment by Sesu8642** [comment]
I moved your idea to #4. Closing this issue.
