### ISSUE TITLE
Crash when starting second game

### ISSUE THREAD

**Issue by niboan** [Sesu8642/FeudalTactics#48]
If you play a game to the end (continue when the enemy gives up), and start another game, the game crashes just before your first turn.
I had hoped it was fixed with a7b10fc, as the symptoms are quite similar, but the problem is still in version 1.1.4.

**Comment by niboan** [comment]
Oh, I hadn't scrolled to the bottom of #40, it seems to be the same problem as described there.

**Comment by Sesu8642** [comment]
No problem. Thanks for reporting. I am trying to reproduce it. How do you exit the first game? Using the "Retry" button or by going back to the main menu and starting a new game from there?

**Comment by niboan** [comment]
I like to completely wipe out the enemy 😉, so I play the game to the end, press exit in the dialog that pops up when they're all gone, and start again from the main menu.

**Comment by Sesu8642** [comment]
Oh, this is the path I missed. Got it. Thanks!
