### ISSUE TITLE
Android Virtual Keyboard covers the Seed's Text Input Box

### ISSUE THREAD

**Issue by Noodlemire** [Sesu8642/FeudalTactics#52]
In both portrait and landscape mode, Android's on-screen keyboard completely covers the little text box where you can type a seed in, making it very annoying to try to input any custom seed. It's still possible to input the seed, you just can't check to make sure you're doing it right without hiding the keyboard over and over again.

Ideally, the seed input box should be able to raise itself over the virtual keyboard to remain visible as you type. Or it could just be at the top of the screen in general, but I can understand not wanting to separate the pre-game settings like that.
![Screenshot_20230412-132825_Feudal_Tactics](https://user-images.githubusercontent.com/27640623/231594697-2feca712-5a32-49de-984f-b067d398a437.jpg)

**Comment by Sesu8642** [comment]
I found this libGDX issue: https://github.com/libgdx/libgdx/issues/3892
Unfortunately, there doesn't seem to be an easy solution. I guess I could detect when the seed input field is focused on Android and then move all the inputs to the top.

**Comment by Sesu8642** [comment]
@mohammaduvez thanks for the tip!
