### ISSUE TITLE
Add adaptive/monochrome app icon for Android 13

### ISSUE THREAD

**Issue by mueller-ma** [Sesu8642/FeudalTactics#53]
For Android 13 apps can provide a monochrome launcher icon that can be used by launchers: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by Sesu8642** [comment]
Seems to be related to adaptive icons in general. I modified the title to include it as well.
Not very high on my priority list right now plus I'm pretty bad at designing stuff. Adding the help wanted label in case someone wants to contribute :)

**Comment by mueller-ma** [comment]
I'd do it, if you like.

Do you have the following logo as SVG somewhere? https://github.com/Sesu8642/FeudalTactics/blob/master/assets/square_logo.png That would make the app a bit smaller.

**Comment by Sesu8642** [comment]
Thanks! I appreciate it.
I don't have it as SVG unfortunately. It more or less originates from an ingame screenshot. I guess I could make a fairly simple SVG version of that with non-pixelated outlines but it could take a couple of days until I find the time. I suggest you use the png for now and I replace it with the SVG once/if I ever make one.

**Comment by Sesu8642** [comment]
Nevermind. It was fairly straight forward. Will this do?
Inkscape file:
![logo_inkscape](https://user-images.githubusercontent.com/45859254/233199487-d6e97128-d859-46e9-b025-9ec88a6af034.svg)

Plain SVG:
![logo_plain](https://user-images.githubusercontent.com/45859254/233199492-98493813-b23e-4604-aece-629becd48471.svg)
