### ISSUE TITLE
preferences forgotten with flatpak

### ISSUE THREAD

**Issue by doniks** [Sesu8642/FeudalTactics#58]
When using the desktop version installed via flatpak, it seems that preferences are not kept when I close and reopen. 

I'm using 

```
Feudal Tactics                                     de.sesu8642.feudaltactics                                           1.1.5                 stable                   system
```

on Ubuntu 22.04.2 LTS

I change show enemy turns to false, but next time it is true again. also it doesn't remember cpu difficulty, map size and map density.

**Comment by Sesu8642** [comment]
Thanks for letting me know. No idea how I didn't notice until now...
Persistence is broken completely. I used Flatseal to grant access to ~/.prefs and it started working. Ideally, the Flatpak version write the files in its sandbox but I'm not sure if libGDX allows that.

**Comment by Sesu8642** [comment]
There is [this PR](https://github.com/libgdx/libgdx/pull/6614) which should enable the proper behavior in libDGX. I am adding the permission in [this PR](https://github.com/flathub/de.sesu8642.feudaltactics/pull/6).

**Comment by Sesu8642** [comment]
Not sure when the fix will be rolled out by Flathub. Maybe only when I do the next update. Keeping this open for now.
