### ISSUE TITLE
Please give feedback about 1.2.0 Release Candidate

### ISSUE THREAD

**Issue by Sesu8642** [Sesu8642/FeudalTactics#61]
I just published a [release candidate for 1.2.0](https://github.com/Sesu8642/FeudalTactics/releases/tag/v1.2.0-1RC).
Since I did some refactoring I would like some users to try the release and report potential bugs in this thread. If you read this and have some time, please help. Also make sure to report back if you tested it and didn't find any issues.

**Comment by Go-rom** [comment]
Ok i'm in

I'll report back next week

**Comment by Sesu8642** [comment]
Thanks! :)

**Comment by Go-rom** [comment]
Everything has been tested (menus, tutorial) and I have played 10-15 games with different settings, no issues encountered whatsoever so I would say so far so good.

**Comment by Sesu8642** [comment]
Thank you! I received positive feedback from one other person via email. I will publish the release once I find the time.
