### ISSUE TITLE
Move random seed button away from start game button

### ISSUE THREAD

**Issue by Sesu8642** [Sesu8642/FeudalTactics#63]
Suggestion i received via email. It can happen relatively easily that you want to re-generate the map and then accidentally start the game. Should be already somewhat improved by the new gap between the buttons. But it shouldnt hurt to move the seed button further up.

**Comment by Konebachirou** [comment]
Hello @Sesu8642, I want to participe on your project and try to fix this  issue

**Comment by Sesu8642** [comment]
Hi @Konebachirou,
Thanks, I appretiate it! Let me know if you need some guidance. This is a good issue for a first contribution.
Please make sure you agree with the [CLA](https://github.com/Sesu8642/FeudalTactics/blob/master/CLA.md) before starting any work and sign it in your PR.

**Comment by Konebachirou** [comment]
Hello @Sesu8642, I work on Windows and I notice that to run the project you have to be on a Unix OS either lunix or mac so I would like to know if you have solutions for running it on Windows otherwise I can open an issue for that since I had to use a VM

**Comment by Sesu8642** [comment]
I do personally use Linux but I'm not aware of any issues on Windows. Can you please provide more details on what the problem is?

**Comment by Konebachirou** [comment]
when i try to run the project on windows i get compilation errors like
Could not get file details of C:\Users\[usrname]\Desktop\FeudalTactics\core\[C:\Users\Users\[usrname]\Desktop\FeudalTactics\core\resources, 
C:\Users\Users\[usrname]\Desktop\FeudalTactics\core\build\generated\resources]: could not file attributes (errno 123)

**Comment by Sesu8642** [comment]
I could confirm this using a Win 11 VM with the latest Temurin 17. Will try to fix it soon but it doesn't seem to be trivial.

**Comment by Sesu8642** [comment]
@Konebachirou I pushed a change on master. Would you mind giving it a try? I tested in my VM but I had the feeling that I tried the same change before and it didn't work the first time.

**Comment by Konebachirou** [comment]
ok no problem  i'ill try

**Comment by Sesu8642** [comment]
solved in bf38f24fe4fbefccbfd9b058c6fe9b5149f30dc6
