### ISSUE TITLE
Adversaries do illegal moves

### ISSUE THREAD

**Issue by xfarrow** [Sesu8642/FeudalTactics#72]
Adversaries are able to make illegal moves. For example a simple peasant can not conquer 3 tiles in a single move. If the game allowed to see singular moves instead of the total moves one could be able to catch these details.

Thank you for your work.

**Comment by Sesu8642** [comment]
Thanks for reporting! Showing individual moves is currently not possible as a result of how the bots are programmed. They are indeed not restricted in the same ways a player is. Namely, they are able to pick up all of their units at once and place them optimally. However, the behavior you describe should obviously not be possible.

Would you be able to provide me with some instructions on how to reproduce the issue? A screen capture or copy of the savegame before the bot turns would be ideal.

**Comment by xfarrow** [comment]
@Sesu8642 thank you for your response. I will try as soon as possible to provide the requested details. Have a great rest of the day :)

**Comment by Sesu8642** [comment]
I attempted to write a unit test that counted the number of tiles before and after a bots turn. The idea was this:
`assertTrue(amountOfTilesAfterTurn <= amountOfTilesBeforeTurn + amountOfUnitsAfterTurn);`

The test failed a few times. However, I discovered that there was an easy explanation: connecting to single kingdomless tiles. I checked some of the failing tests and all of them could be explained by that. Of course thats not perfect but I don't believe there's something wrong here.

Closing this for now but feel free to re-open when you can reproduce :)
