### ISSUE TITLE
Color change for top text

### ISSUE THREAD

**Issue by rickdaheals** [Sesu8642/FeudalTactics#89]
White is a difficult color to read when it is on certain backgrounds (white, yellow, light blue, pink). I often find myself adjusting the map to move the white text on to a dark blue or brown background. I'd suggest changing the savings and income text color to something other than white. 

![Screenshot_20241123-070848](https://github.com/user-attachments/assets/1e513059-4795-4084-b0b8-c9aa5b4dc156)

![Screenshot_20241123-070831](https://github.com/user-attachments/assets/02a5638a-37d9-4a3f-900f-936457914353)

![Screenshot_20241123-070815](https://github.com/user-attachments/assets/2ab25744-4121-488b-b969-b28d9fb83c09)

![Screenshot_20241123-070802](https://github.com/user-attachments/assets/c452e090-bf10-4079-b51e-f72e417df2a7)

**Comment by Photosounder** [comment]
I think the simplest way to deal with something like this is to darker the background under the text (like with a rectangle).

**Comment by Sesu8642** [comment]
I believe it's the same as #15. Closing this and tracking it there.
I do notice a high interest in this recently. Gonna prioritize accordingly.
