### ISSUE TITLE
Escape Key For "Undo" Button

### ISSUE THREAD

**Issue by teeks99** [Sesu8642/FeudalTactics#9]
(Desktop) When you have someone selected, it seems like the "Esc" key is the natural one to de-select. However, clicking that takes you back to the main menu (pause action....incidentally pause is an odd concept for a turn based game).

Could it be updated so that if a selection is active, it de-selects that on the first press. Then another esc will take you back to the main menu.

(Android) Interestingly this already works with the back button in the android client. Though there isn't a general convention I'm aware of [this person](https://paperlined.org/apps/android/hardware_keyboard.html) indicated that they also think esc should perform the equivalent of the back button.

Ahhh, but the back button in android *doesn't* go back to the main menu.

**Comment by Sesu8642** [comment]
In desktop games, I usually expect the Esc key to pause the game and/or open the menu.

On Android, the back button is mapped to the "undo" functionality. I think that it could confuse some players if the Esc key would sometimes bring up the menu and sometimes function as the undo key.

Many mice have a back button as well. That could be mapped to the undo action on Desktop as well.

**Comment by teeks99** [comment]
I do like the idea of mapping the back button.

I still think that Esc is a natural for "get out of this mode", but your call. Maybe I'm trained by the Android back button to get out of the mode first, then the next tap gets me back to the menu.
