### ISSUE TITLE
Animations stop moving normally

### ISSUE THREAD

**Issue by Photosounder** [Sesu8642/FeudalTactics#90]
It might have to do with the game being open for several days, but the animations aren't working properly anymore, the frames only change sometimes. Maybe the number to track time is getting too big 🤷‍♂️

https://github.com/user-attachments/assets/435eb744-f0ad-4cc5-91ac-c8394670f354

**Comment by Sesu8642** [comment]
Interesting. I might have programmed the animation in a hacky way. :D
It could also be Windows specific. I don't test there very often. Need to investigate.

**Comment by Sesu8642** [comment]
Btw what is the reason you keep the game open for so long? Is the autosave feature not working?

**Comment by Photosounder** [comment]
I just keep it open so that I don't have to relaunch it when I want to play another little game. I kind of play it throughout the day to avoid falling asleep 😁. So most of the time it's in the menu. Anyway the animations for the same game worked fine again when I relaunched it, but that was to be expected.

**Comment by Sesu8642** [comment]
https://github.com/libgdx/libgdx/issues/7536

**Comment by Sesu8642** [comment]
Fixed in 1.3.1. Please update :)

**Comment by Photosounder** [comment]
Excellent, thank you 😊
