### ISSUE TITLE
Stalemate (impossible to progress)

### ISSUE THREAD

**Issue by Lurler** [Sesu8642/FeudalTactics#91]
This is not strictly a bug, but if you play on a "loose" map and there is a narrow choke point (corridor of tiles) the enemy will position their baron on one side while your baron stands on another side and neither can progress. Basically resulting in a complete stalemate where neither side can win. You can of course remove your troops from the choke point and allow the AI to take it, but it will obviously only make it worse for you, so doing that would only result in losing the game.

**How to fix:** a simple solution to that problem would be allow barons to fight each other, but since they are of the same power level it can be done such that after the fight the tile is not taken and both barons simply disappear. Or alternatively you can add another unit type that is weaker than all other, but allows defeating barons. Basically the stalemate situation needs to be prevented as otherwise the loose map type is unplayable due to this stalemate arising in almost all games.

**Comment by Sesu8642** [comment]
There has been some discussion about stalemates in #28. Feel free to continue the discussion there. Your ideas are interesting for sure.
I don't want to add another unit type at this point. Barons being able to fight each other is a possible solution.
