### ISSUE TITLE
find forgotten kingdom 

### ISSUE THREAD

**Issue by doniks** [Sesu8642/FeudalTactics#92]
I frequently get the warning that I have forgotten to make a move for some kingdom(s), but I struggle to find that kingdom. It would be great if this could be more convenient.

It happens more often in the beginning when there is a large number of small kingdoms. 

Fwiw, I mostly play XXLarge, Loose. I just note this in case it might be relevant for the reproduction of this situation.

**Comment by doniks** [comment]
I'm not completely sure what the best user experience would be, maybe pan to an unplayed kingdom? Or select? Or both, or pan+zoom? Or pan+zoom+select, or ...

**Comment by Sesu8642** [comment]
I think its the same as https://github.com/Sesu8642/FeudalTactics/issues/88. Feel free too add any additional comments there.

Zooming would be complicated to implement so probably it will be pan+select for the first iteration.
